package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"graphql-go/core/stats"
	"graphql-go/graph/model"
)

// BurgerStats is the resolver for the burgerStats field.
func (r *queryResolver) BurgerStats(ctx context.Context) (*model.BurgerStats, error) {
	res, error := stats.CalculateBurgerStats(r.DB)

	return stats.BurgerStatsToModel(res), error
}
