// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type BurgerStats struct {
	TotalOrders     int         `json:"totalOrders"`
	TotalBurgerDays int         `json:"totalBurgerDays"`
	TopConsumers    []*Consumer `json:"topConsumers"`
}

type Consumer struct {
	User            *User `json:"user"`
	TotalOrders     int   `json:"totalOrders"`
	TotalBurgerDays int   `json:"totalBurgerDays"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type SpecialOrders string

const (
	SpecialOrdersNoBacon         SpecialOrders = "no_bacon"
	SpecialOrdersNoCheese        SpecialOrders = "no_cheese"
	SpecialOrdersNoSalat         SpecialOrders = "no_salat"
	SpecialOrdersGarlicMayo      SpecialOrders = "garlic_mayo"
	SpecialOrdersChiliMayo       SpecialOrders = "chili_mayo"
	SpecialOrdersGlutenFreeBun   SpecialOrders = "gluten_free_bun"
	SpecialOrdersVegetarianPatty SpecialOrders = "vegetarian_patty"
)

var AllSpecialOrders = []SpecialOrders{
	SpecialOrdersNoBacon,
	SpecialOrdersNoCheese,
	SpecialOrdersNoSalat,
	SpecialOrdersGarlicMayo,
	SpecialOrdersChiliMayo,
	SpecialOrdersGlutenFreeBun,
	SpecialOrdersVegetarianPatty,
}

func (e SpecialOrders) IsValid() bool {
	switch e {
	case SpecialOrdersNoBacon, SpecialOrdersNoCheese, SpecialOrdersNoSalat, SpecialOrdersGarlicMayo, SpecialOrdersChiliMayo, SpecialOrdersGlutenFreeBun, SpecialOrdersVegetarianPatty:
		return true
	}
	return false
}

func (e SpecialOrders) String() string {
	return string(e)
}

func (e *SpecialOrders) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SpecialOrders(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SpecialOrders", str)
	}
	return nil
}

func (e SpecialOrders) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
