name: build_image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_REGISTRY }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/${{ secrets.repository }}:latest
